default: &default
  adapter: postgresql
  user: postgres
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: algo-tools-development

test:
  <<: *default
  database: algo-tools-test

production:
  <<: *default
  database: algo-tools
  username: algo-tools
  password: <%= ENV['ALGO_TOOLS_DATABASE_PASSWORD'] %>
